title: Test
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
permalink: pretty
permalink: /:title/
collections:
  _pages:
    output: true
include: [_pages]
defaults:
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
