title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
permalink: pretty
permalink: "/:title:output_ext"
collections:
  _pages:
    output: true
    include:
  - _pages
